### PR TITLE
Bump lootbox, making this buildable with stack 2

### PR DESCRIPTION
**Pull request by zhenyavinogradov**
## Description

diff: https://github.com/serokell/lootbox/compare/4700376b8493f6ac164461715cb72a0259148ac2...18ced0d493348b4d6bae8517dff7ee6de6e0c9d9

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](/README.md)
    - Haddock

- Public contracts
  - [ ] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [ ] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [ ] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [ ] My code complies with the [style guide](docs/code-style.md).

### CODE REVIEW

**Comment by Martoon-00** [comment]
Now it seems that whenever I need to change a dependency, too many places have to be updated. Is it possible to instead explain to a user how to get `stack.yaml.lock` file, or in a pinch, generate it automatically in CI?

**Comment by gromakovsky** [comment]
`stack.yaml.lock` file is generated automatically when you run something like `stack build` AFAIK.

**Comment by balsoft** [comment]
@Martoon-00 the nix part will be static once #12 (and/or it's upstream counterpart) is merged.

**Comment by Martoon-00** [comment]
> stack.yaml.lock file is generated automatically when you run something like stack build AFAIK.

@gromakovsky Yes, but only if built with stack 2.*. 

> the nix part will be static once #12 (and/or it's upstream counterpart) is merged.

Ah right, I remembered it's being once said, nice.

**Comment by zhenyavinogradov** [comment]
stack.yaml.lock getting out of sync is not a big problem. But if you don't want that to happen, generate it with stack 2

**Comment by gromakovsky** [comment]
I personally would treat it as an auxiliary not-required-to-keep-up-to-date file. So if someone with `stack-2` comes, runs `stack build` and sees that it is updated, they are welcome to push updated version. But if someone who uses something else comes and updates dependencies but doesn't update the lock file, we don't care, someone else will update it later.

To me this file seems quite unimportant to care about keeping it up to date, but maybe I am wrong.

**Comment by Martoon-00** [comment]
Fair enough, now I see.

**Pull request merged**
